shell = "bash -c '{}'"

[[item]]
file = "~/.base16_theme"
template = "shell"
rewrite = true
hook = "bash ~/dotfiles/flavours/reload-shell.sh"

[[item]]
file = "~/.fzf.colors"
template = "fzf"
rewrite = true

[[item]]
file = "~/.config/nvim/colorscheme.vim"
template = "vim"
rewrite = true

[[item]]
file = "~/.config/nvim/airline-colors.vim"
template = "vim-airline-themes"
rewrite = true

[[item]]
file = "~/.config/powerline/colors.json"
template = "powerline"
rewrite = true
