#!/bin/sh
initial="$(hyprctl activewindow -j | jq --raw-output .title)"
if ! [ "$initial" = "null" ]; then
    echo "$initial"
fi
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep '^activewindow>>' | stdbuf -o0 awk -F '>>|,' '{print $3}'
