#!/bin/bash
initial="$(hyprctl activewindow -j | jq --raw-output .title)"
if ! [ "$initial" = "null" ]; then
    echo "$initial"
fi

exec 4< <(socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep '^activewindow>>' | stdbuf -o0 awk -F '>>|,' '{print $3}')
exec 5< <(socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep '^activewindow2>>' | stdbuf -o0 awk -F '>>|,' '{print $3}')
exec 6< <(socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep '^closewindow>>' | stdbuf -o0 awk -F '>>|,' '{print $3}')

# print window title
while read -r line; do
    echo "$line"
done <&4 &

# window close
while read -r line; do
    ACTIVE_WINDOW="$line"
done <&5 &

# clear on window close
while read -r line; do
    if [[ "$line" == "$ACTIVE_WINDOW" ]]; then
        echo ""
    fi
done <&6 &

wait $(jobs -p)
